language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due
- BOARD=genuino101
- BOARD=zero

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done

notifications:
  flowdock:
    # main flow
    - secure: "eU9WtveHbe8Eg8XlAGEWXOMugQquh4GUPhsuKwPo7GBWsjESjWee1WVoDYWY5pvz3bBh39C8J9PU3SgWWfP1TKLmam+rXLBQ8b3pS8toUbzl92OqYv6JmFlFC/k+YMHNZDaJmLN+KQMkVqs0qTTv69HVGsvCAlnqc5KGSmh7DwUTJBiA9fvPAELcLGFxMtO3YcYc8+6QFbyYT86XPdLgc3qCRRLSXJcTsoTWoCtvQ8CBoamf62ykubll0CfcJDO1IFLWvpZjE2+0k7VUFnjE9ifmwwzsaZ9WUqxFdorieeVZZJezzB4C5pUwYfb93dViuj1b16Eztrw/CXGT0dFvav8WMiOQpS74WmerqhAcvHLoAwc73eYQMFmnuNdwW4hkR3oSTQJ+yQFBF4I7awcFmhWBsCLNbDcxmXopamOkCbvqMvFqroHxzOmE3K6bMD1D0A3g+mKL/6B1clgdxBzXdwRmHkq3ODyrwlf9R77eiKmJaLbu4CmacVIkCad59ofub5G6tGGXWX28pep5BuuUzLs3nJaEI1s+yEH3Tftba6zX1jRjIChqpnch0zr04h9f/Dx4RC4WjZNO/7BhgOCANZy0O/0k5EI0qds2QCPPvccORsCVNmrOFeTR7dYl1Zi7isfXPfuNHv+RaSPicS6noxk34A6qkadqKaHk9WQtgfs="
    # software team
    - secure: "XyGNdaItM/0YrYHiv5PcDyuRXYyvA/BoY74diSreSxZtTTSgUEvDMB7dM7Hz65MPCZEvguZiB8qiNqYqtfpJPtGD8wsvT30jhesBDOaWSKPHv4qDxRJNMPP0H4JRDUCON1nphxhlmmsKrLfL69bnjiVAtqX171Vv/SLnGqy5LClhMZvq3cdCaBpb0Qi0FwR0wxQgOmLPiP/+z5fWmU8aS53S+IHbGTtZXNieqCWGVGBlP6WnDjq71+FC8Gg2D8KT4SuKpvZ08n+e+JuWUeQ2RXZNJ4H0SSNQY+gyW17jkI9S+zpEnZomq/Hq/4afsSXhUDU0IO/8osLjdK5/kuaUsvWbnxSd3IrKImvwWZI40P20E2WPbLMagQBaghrDwEOBYfudLwfmsCwzEekJEgBmj2NVB+LvqSJRGFk5UBFE5coibkSStCS86ob9OBs9W+po4EREZjSLuXg3xJ3CTDz1A69OydwkgtLTUwXcX2IvEPXhcfZMuJ9NGYNNVUcphpnWQZofFm7eZ1LSHOPnpE3KSHGnzEi6qrd6bhhmjVq2Neeu3B8wKa9YFCNLeC1GE+vmQl3lt5QPduBv55OUyE9KnxgJt+0NRfs2Z76JMdouUDaPUULCUlYKmlr1iTtzsERqZmSTLygB6HPO/Dbcy6LPLq0b3nGKVh0fWm7iD6PZuK8="
